imports:
    - { resource: config.yml }

doctrine:
    orm:
        dql:
            string_functions:
                substring_index: Bigfoot\Bundle\CoreBundle\ORM\Doctrine\Query\PgSQL\SubstringIndex
